version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.11.1
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys: # add SSH key with write access
          fingerprints:
            - "02:d5:63:28:6b:94:5d:76:08:42:ab:1e:b2:b7:80:bb"
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          # 1.0.0-alpha.27 still is not stable
          command: npm install vuepress@^1.0.0-alpha.27 yarn && yarn
      - run:
          name: Publish update to GitHub
          command: bash ./deploy.sh
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: dev
