version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.11.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-cache-{{ .Branch }}
            - npm-cache-
      - run:
          name: Install dependencies
          command: sudo npm install -g vuepress
      - save_cache:
          key: npm-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths: node_modules
  deploy-develop:
    docker:
      - image: circleci/node:9.11.1
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:  # add SSH key with write access
          fingerprints:
            - "e6:c1:02:7d:3c:26:12:c4:ed:e3:95:43:46:29:66:0a"
      - restore_cache:
          keys:
            - npm-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-cache-{{ .Branch }}
            - npm-cache-
      - run:
          name: Install dependencies
          command: sudo npm install -g vuepress
      # - run:
      #     name: Update Git to use worktree feature
      #     command: |
      #       sudo apt-get remove git -y
      #       sudo apt-get install software-properties-common
      #       sudo sudo apt-get install dh-autoreconf libcurl4-gnutls-dev libexpat1-dev gettext libz-dev libssl-dev -y
      #       cd /tmp
      #       curl -L --progress https://github.com/git/git/archive/v2.17.0.tar.gz | tar xz
      #       cd git-2.17.0/
      #       make configure
      #       ./configure --prefix=/usr
      #       sudo make install
      - run:
          name: Publish update to GitHub
          command: bash ./deploy.sh
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-develop:
          requires:
            - build
          filters:
            branches:
              only: develop
