version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.11.1
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:  # add SSH key with write access
          fingerprints:
            - "9d:d7:ca:e3:c1:08:79:2f:2d:b3:c3:95:06:4e:70:a8"
      # - restore_cache:
      #     keys:
      #       - npm-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      #       - npm-cache-{{ .Branch }}
      #       - npm-cache-
      - run:
          name: Install dependencies
          command: npm install -g vuepress && npm install
      - run:
          name: Publish update to GitHub
          command: bash ./deploy.sh
      # - save_cache:
      #     key: npm-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      #     paths: node_modules
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: dev
