version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.11.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-cache-{{ .Branch }}
            - npm-cache-
      - run:
          name: Install dependencies
          command: sudo npm install -g vuepress
      - save_cache:
          key: npm-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths: node_modules
  deploy-dev:
    docker:
      - image: circleci/node:9.11.1
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:  # add SSH key with write access
          fingerprints:
            - "f6:7e:6e:47:cb:85:ae:02:f5:97:72:bb:37:bd:7e:7f"
      - restore_cache:
          keys:
            - npm-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-cache-{{ .Branch }}
            - npm-cache-
      - run:
          name: Install dependencies
          command: sudo npm install -g vuepress
      - run:
          name: Publish update to GitHub
          command: bash ./deploy.sh
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-dev:
          requires:
            - build
          filters:
            branches:
              only: dev
